// <auto-generated />
using LibreriaFinale.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibreriaFinale.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibreriaFinale.Model.Libro", b =>
                {
                    b.Property<string>("ISBN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Anno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Autore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ISBN");

                    b.ToTable("SetLibri");

                    b.HasData(
                        new
                        {
                            ISBN = "9788804512770",
                            Anno = "1954",
                            Autore = "J.R.R. Tolkien",
                            Genere = "Fantasy",
                            Titolo = "Il signore degli anelli"
                        },
                        new
                        {
                            ISBN = "9780747532699",
                            Anno = "1997",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e la Pietra Filosofale"
                        },
                        new
                        {
                            ISBN = "9780747538493",
                            Anno = "1998",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e la Camera dei Segreti"
                        },
                        new
                        {
                            ISBN = "9780747545118",
                            Anno = "1999",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e il Prigioniero di Azkaban"
                        },
                        new
                        {
                            ISBN = "9780747551003",
                            Anno = "2000",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e il Calice di Fuoco"
                        },
                        new
                        {
                            ISBN = "9780747551010",
                            Anno = "2003",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e l'Ordine della Fenice"
                        },
                        new
                        {
                            ISBN = "9780747581086",
                            Anno = "2005",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e il Principe Mezzosangue"
                        },
                        new
                        {
                            ISBN = "9780747595824",
                            Anno = "2007",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e i Doni della Morte"
                        },
                        new
                        {
                            ISBN = "9788806188034",
                            Anno = "1320",
                            Autore = "Dante Alighieri",
                            Genere = "Poesia epica",
                            Titolo = "Divina Commedia"
                        },
                        new
                        {
                            ISBN = "9788806172361",
                            Anno = "1949",
                            Autore = "George Orwell",
                            Genere = "Distopia",
                            Titolo = "1984"
                        },
                        new
                        {
                            ISBN = "9788806221168",
                            Anno = "1813",
                            Autore = "Jane Austen",
                            Genere = "Romanzo",
                            Titolo = "Orgoglio e Pregiudizio"
                        },
                        new
                        {
                            ISBN = "9788806173150",
                            Anno = "1847",
                            Autore = "Emily Bront�",
                            Genere = "Romanzo",
                            Titolo = "Cime tempestose"
                        },
                        new
                        {
                            ISBN = "9780156012195",
                            Anno = "1943",
                            Autore = "Antoine de Saint-Exup�ry",
                            Genere = "Romanzo",
                            Titolo = "Il Piccolo Principe"
                        },
                        new
                        {
                            ISBN = "9780156037136",
                            Anno = "1980",
                            Autore = "Umberto Eco",
                            Genere = "Romanzo giallo",
                            Titolo = "Il nome della rosa"
                        },
                        new
                        {
                            ISBN = "9780261103344",
                            Anno = "1937",
                            Autore = "J.R.R. Tolkien",
                            Genere = "Fantasy",
                            Titolo = "Lo Hobbit"
                        },
                        new
                        {
                            ISBN = "9780066238500",
                            Anno = "1950",
                            Autore = "C.S. Lewis",
                            Genere = "Fantasy",
                            Titolo = "Le cronache di Narnia"
                        },
                        new
                        {
                            ISBN = "9780142437247",
                            Anno = "1851",
                            Autore = "Herman Melville",
                            Genere = "Romanzo",
                            Titolo = "Moby Dick"
                        },
                        new
                        {
                            ISBN = "9780142437230",
                            Anno = "1605",
                            Autore = "Miguel de Cervantes",
                            Genere = "Romanzo",
                            Titolo = "Don Chisciotte"
                        },
                        new
                        {
                            ISBN = "9780140449266",
                            Anno = "1844",
                            Autore = "Alexandre Dumas",
                            Genere = "Romanzo",
                            Titolo = "Il conte di Montecristo"
                        },
                        new
                        {
                            ISBN = "9780140449174",
                            Anno = "1877",
                            Autore = "Lev Tolstoj",
                            Genere = "Romanzo",
                            Titolo = "Anna Karenina"
                        },
                        new
                        {
                            ISBN = "9781400079988",
                            Anno = "1869",
                            Autore = "Lev Tolstoj",
                            Genere = "Romanzo",
                            Titolo = "Guerra e Pace"
                        },
                        new
                        {
                            ISBN = "9780316769488",
                            Anno = "1951",
                            Autore = "J.D. Salinger",
                            Genere = "Romanzo",
                            Titolo = "Il giovane Holden"
                        },
                        new
                        {
                            ISBN = "9780060883287",
                            Anno = "1967",
                            Autore = "Gabriel Garc�a M�rquez",
                            Genere = "Romanzo",
                            Titolo = "Cent'anni di solitudine"
                        },
                        new
                        {
                            ISBN = "9780684801223",
                            Anno = "1952",
                            Autore = "Ernest Hemingway",
                            Genere = "Romanzo",
                            Titolo = "Il vecchio e il mare"
                        },
                        new
                        {
                            ISBN = "9780743273565",
                            Anno = "1925",
                            Autore = "F. Scott Fitzgerald",
                            Genere = "Romanzo",
                            Titolo = "Il grande Gatsby"
                        },
                        new
                        {
                            ISBN = "9780486415871",
                            Anno = "1866",
                            Autore = "F�dor Dostoevskij",
                            Genere = "Romanzo",
                            Titolo = "Delitto e castigo"
                        },
                        new
                        {
                            ISBN = "9780486278070",
                            Anno = "1890",
                            Autore = "Oscar Wilde",
                            Genere = "Romanzo",
                            Titolo = "Il ritratto di Dorian Gray"
                        },
                        new
                        {
                            ISBN = "9780805209990",
                            Anno = "1925",
                            Autore = "Franz Kafka",
                            Genere = "Romanzo",
                            Titolo = "Il processo"
                        },
                        new
                        {
                            ISBN = "9780679720201",
                            Anno = "1942",
                            Autore = "Albert Camus",
                            Genere = "Romanzo",
                            Titolo = "Lo straniero"
                        },
                        new
                        {
                            ISBN = "9780143108276",
                            Anno = "1967",
                            Autore = "Michail Bulgakov",
                            Genere = "Romanzo",
                            Titolo = "Il maestro e Margherita"
                        },
                        new
                        {
                            ISBN = "9780062073563",
                            Anno = "1926",
                            Autore = "Agatha Christie",
                            Genere = "Romanzo giallo",
                            Titolo = "L'assassinio di Roger Ackroyd"
                        },
                        new
                        {
                            ISBN = "9780486266848",
                            Anno = "1898",
                            Autore = "Henry James",
                            Genere = "Romanzo",
                            Titolo = "Il giro di vite"
                        },
                        new
                        {
                            ISBN = "9780486451473",
                            Anno = "1830",
                            Autore = "Stendhal",
                            Genere = "Romanzo",
                            Titolo = "Il rosso e il nero"
                        },
                        new
                        {
                            ISBN = "9781593082089",
                            Anno = "1857",
                            Autore = "Gustave Flaubert",
                            Genere = "Romanzo",
                            Titolo = "Madame Bovary"
                        },
                        new
                        {
                            ISBN = "9780141439778",
                            Anno = "1759",
                            Autore = "Laurence Sterne",
                            Genere = "Romanzo comico",
                            Titolo = "Vita e opinioni di Tristram Shandy, gentiluomo"
                        },
                        new
                        {
                            ISBN = "9780486400778",
                            Anno = "1876",
                            Autore = "Mark Twain",
                            Genere = "Romanzo",
                            Titolo = "Le avventure di Tom Sawyer"
                        },
                        new
                        {
                            ISBN = "9780486280615",
                            Anno = "1884",
                            Autore = "Mark Twain",
                            Genere = "Romanzo",
                            Titolo = "Le avventure di Huckleberry Finn"
                        },
                        new
                        {
                            ISBN = "9788899060694",
                            Anno = "1904",
                            Autore = "Emilio Salgari",
                            Genere = "Avventura",
                            Titolo = "La regina dei Caraibi"
                        },
                        new
                        {
                            ISBN = "9780486266885",
                            Anno = "1886",
                            Autore = "Robert Louis Stevenson",
                            Genere = "Romanzo",
                            Titolo = "Il dottor Jekyll e Mr. Hyde"
                        },
                        new
                        {
                            ISBN = "9780743277709",
                            Anno = "1972",
                            Autore = "Richard Adams",
                            Genere = "Romanzo",
                            Titolo = "La collina dei conigli"
                        },
                        new
                        {
                            ISBN = "9780451526345",
                            Anno = "1945",
                            Autore = "George Orwell",
                            Genere = "Romanzo",
                            Titolo = "La fattoria degli animali"
                        },
                        new
                        {
                            ISBN = "9780451526346",
                            Anno = "1945",
                            Autore = "George Orwell",
                            Genere = "Romanzo",
                            Titolo = "La fattoria degli animali"
                        },
                        new
                        {
                            ISBN = "9780486440896",
                            Anno = "1874",
                            Autore = "Jules Verne",
                            Genere = "Avventura",
                            Titolo = "L'isola misteriosa"
                        },
                        new
                        {
                            ISBN = "9780486440889",
                            Anno = "1868",
                            Autore = "Jules Verne",
                            Genere = "Avventura",
                            Titolo = "I figli del capitano Grant"
                        },
                        new
                        {
                            ISBN = "9780486440872",
                            Anno = "1870",
                            Autore = "Jules Verne",
                            Genere = "Avventura",
                            Titolo = "Venti mila leghe sotto i mari"
                        },
                        new
                        {
                            ISBN = "9781841499713",
                            Anno = "1990",
                            Autore = "Terry Brooks",
                            Genere = "Fantasy",
                            Titolo = "Gli eredi di Shannara"
                        },
                        new
                        {
                            ISBN = "9780345298974",
                            Anno = "1977",
                            Autore = "Terry Brooks",
                            Genere = "Fantasy",
                            Titolo = "La spada di Shannara"
                        },
                        new
                        {
                            ISBN = "9780345375569",
                            Anno = "1992",
                            Autore = "Terry Brooks",
                            Genere = "Fantasy",
                            Titolo = "La regina degli elfi di Shannara"
                        },
                        new
                        {
                            ISBN = "9780345375552",
                            Anno = "1993",
                            Autore = "Terry Brooks",
                            Genere = "Fantasy",
                            Titolo = "I Talismani di Shannara"
                        },
                        new
                        {
                            ISBN = "9780345331404",
                            Anno = "1992",
                            Autore = "Terry Brooks",
                            Genere = "Fantasy",
                            Titolo = "La Canzone di Shannara"
                        },
                        new
                        {
                            ISBN = "9780553103540",
                            Anno = "1996",
                            Autore = "George R.R. Martin",
                            Genere = "Fantasy",
                            Titolo = "Il trono di spade"
                        },
                        new
                        {
                            ISBN = "9780618260270",
                            Anno = "1954",
                            Autore = "J.R.R. Tolkien",
                            Genere = "Fantasy",
                            Titolo = "Le due torri"
                        },
                        new
                        {
                            ISBN = "9780618260553",
                            Anno = "1955",
                            Autore = "J.R.R. Tolkien",
                            Genere = "Fantasy",
                            Titolo = "Il ritorno del re"
                        },
                        new
                        {
                            ISBN = "9780486275438",
                            Anno = "1865",
                            Autore = "Lewis Carroll",
                            Genere = "Fantasia",
                            Titolo = "Alice nel Paese delle Meraviglie"
                        },
                        new
                        {
                            ISBN = "9780486291162",
                            Anno = "1900",
                            Autore = "L. Frank Baum",
                            Genere = "Fantasia",
                            Titolo = "Il Mago di Oz"
                        },
                        new
                        {
                            ISBN = "9780486282115",
                            Anno = "1883",
                            Autore = "Carlo Collodi",
                            Genere = "Fantasia",
                            Titolo = "Pinocchio"
                        },
                        new
                        {
                            ISBN = "9780486404272",
                            Anno = "1719",
                            Autore = "Daniel Defoe",
                            Genere = "Romanzo",
                            Titolo = "Robinson Crusoe"
                        },
                        new
                        {
                            ISBN = "9780486424515",
                            Anno = "1862",
                            Autore = "Victor Hugo",
                            Genere = "Romanzo",
                            Titolo = "I miserabili"
                        },
                        new
                        {
                            ISBN = "9780486424492",
                            Anno = "1847",
                            Autore = "Charlotte Bront�",
                            Genere = "Romanzo",
                            Titolo = "Jane Eyre"
                        },
                        new
                        {
                            ISBN = "9780486437911",
                            Anno = "1880",
                            Autore = "F�dor Dostoevskij",
                            Genere = "Romanzo",
                            Titolo = "I fratelli Karamazov"
                        },
                        new
                        {
                            ISBN = "9780486290300",
                            Anno = "1915",
                            Autore = "Franz Kafka",
                            Genere = "Romanzo",
                            Titolo = "La metamorfosi"
                        },
                        new
                        {
                            ISBN = "9780486282114",
                            Anno = "1818",
                            Autore = "Mary Shelley",
                            Genere = "Romanzo",
                            Titolo = "Frankenstein"
                        },
                        new
                        {
                            ISBN = "9780486411095",
                            Anno = "1897",
                            Autore = "Bram Stoker",
                            Genere = "Romanzo",
                            Titolo = "Dracula"
                        },
                        new
                        {
                            ISBN = "9780486453941",
                            Anno = "1839",
                            Autore = "Stendhal",
                            Genere = "Romanzo",
                            Titolo = "La Certosa di Parma"
                        },
                        new
                        {
                            ISBN = "9780486451954",
                            Anno = "1831",
                            Autore = "Honor� de Balzac",
                            Genere = "Romanzo",
                            Titolo = "La pelle di zigrino"
                        },
                        new
                        {
                            ISBN = "9780486295060",
                            Anno = "1898",
                            Autore = "H.G. Wells",
                            Genere = "Fantascienza",
                            Titolo = "La guerra dei mondi"
                        },
                        new
                        {
                            ISBN = "9780486426694",
                            Anno = "1927",
                            Autore = "Marcel Proust",
                            Genere = "Romanzo",
                            Titolo = "Il tempo ritrovato"
                        },
                        new
                        {
                            ISBN = "9780486418309",
                            Anno = "1922",
                            Autore = "James Joyce",
                            Genere = "Romanzo",
                            Titolo = "Ulisse"
                        },
                        new
                        {
                            ISBN = "9780684830490",
                            Anno = "1952",
                            Autore = "Ernest Hemingway",
                            Genere = "Romanzo",
                            Titolo = "Il vecchio e il mare"
                        },
                        new
                        {
                            ISBN = "9780486456232",
                            Anno = "1869",
                            Autore = "F�dor Dostoevskij",
                            Genere = "Romanzo",
                            Titolo = "L'idiota"
                        },
                        new
                        {
                            ISBN = "9780486421118",
                            Anno = "1926",
                            Autore = "Franz Kafka",
                            Genere = "Romanzo",
                            Titolo = "Il castello"
                        },
                        new
                        {
                            ISBN = "9780486272789",
                            Anno = "1603",
                            Autore = "William Shakespeare",
                            Genere = "Teatro",
                            Titolo = "Amleto"
                        },
                        new
                        {
                            ISBN = "9780486275575",
                            Anno = "1604",
                            Autore = "William Shakespeare",
                            Genere = "Teatro",
                            Titolo = "Otello"
                        },
                        new
                        {
                            ISBN = "9780486280586",
                            Anno = "1606",
                            Autore = "William Shakespeare",
                            Genere = "Teatro",
                            Titolo = "Re Lear"
                        },
                        new
                        {
                            ISBN = "9780486278026",
                            Anno = "1606",
                            Autore = "William Shakespeare",
                            Genere = "Teatro",
                            Titolo = "Macbeth"
                        },
                        new
                        {
                            ISBN = "9780486406589",
                            Anno = "1599",
                            Autore = "William Shakespeare",
                            Genere = "Teatro",
                            Titolo = "Enrico V"
                        },
                        new
                        {
                            ISBN = "9780486406590",
                            Anno = "1611",
                            Autore = "William Shakespeare",
                            Genere = "Teatro",
                            Titolo = "La tempesta"
                        },
                        new
                        {
                            ISBN = "9780486406600",
                            Anno = "1607",
                            Autore = "William Shakespeare",
                            Genere = "Teatro",
                            Titolo = "Antonio e Cleopatra"
                        },
                        new
                        {
                            ISBN = "9780486406778",
                            Anno = "1596",
                            Autore = "William Shakespeare",
                            Genere = "Teatro",
                            Titolo = "Il mercante di Venezia"
                        },
                        new
                        {
                            ISBN = "9780486406785",
                            Anno = "1595",
                            Autore = "William Shakespeare",
                            Genere = "Teatro",
                            Titolo = "Sogno di una notte di mezza estate"
                        },
                        new
                        {
                            ISBN = "9780486406822",
                            Anno = "1599",
                            Autore = "William Shakespeare",
                            Genere = "Teatro",
                            Titolo = "Molto rumore per nulla"
                        },
                        new
                        {
                            ISBN = "9780486406846",
                            Anno = "1664",
                            Autore = "Moli�re",
                            Genere = "Teatro",
                            Titolo = "Il Tartufo"
                        },
                        new
                        {
                            ISBN = "9780486411079",
                            Anno = "1320",
                            Autore = "Dante Alighieri",
                            Genere = "Poesia epica",
                            Titolo = "La Divina Commedia"
                        },
                        new
                        {
                            ISBN = "9780486298890",
                            Anno = "632",
                            Autore = "Autori vari",
                            Genere = "Religione",
                            Titolo = "Il Corano"
                        },
                        new
                        {
                            ISBN = "9780486298910",
                            Anno = "0",
                            Autore = "Autori vari",
                            Genere = "Religione",
                            Titolo = "La Bibbia"
                        },
                        new
                        {
                            ISBN = "9780486298911",
                            Anno = "0",
                            Autore = "Autori vari",
                            Genere = "Religione",
                            Titolo = "La Bibbia"
                        },
                        new
                        {
                            ISBN = "9780140275360",
                            Anno = "800 a.C.",
                            Autore = "Omero",
                            Genere = "Poesia epica",
                            Titolo = "Iliade"
                        },
                        new
                        {
                            ISBN = "9780140268867",
                            Anno = "800 a.C.",
                            Autore = "Omero",
                            Genere = "Poesia epica",
                            Titolo = "Odissea"
                        },
                        new
                        {
                            ISBN = "9780140449327",
                            Anno = "19 a.C.",
                            Autore = "Virgilio",
                            Genere = "Poesia epica",
                            Titolo = "Eneide"
                        },
                        new
                        {
                            ISBN = "9780142437222",
                            Anno = "1320",
                            Autore = "Dante Alighieri",
                            Genere = "Poesia epica",
                            Titolo = "Inferno"
                        },
                        new
                        {
                            ISBN = "9780142437233",
                            Anno = "1320",
                            Autore = "Dante Alighieri",
                            Genere = "Poesia epica",
                            Titolo = "Purgatorio"
                        },
                        new
                        {
                            ISBN = "9780142437244",
                            Anno = "1320",
                            Autore = "Dante Alighieri",
                            Genere = "Poesia epica",
                            Titolo = "Paradiso"
                        },
                        new
                        {
                            ISBN = "9780141189579",
                            Anno = "1904",
                            Autore = "Luigi Pirandello",
                            Genere = "Romanzo",
                            Titolo = "Il fu Mattia Pascal"
                        },
                        new
                        {
                            ISBN = "9780141187872",
                            Anno = "1923",
                            Autore = "Italo Svevo",
                            Genere = "Romanzo",
                            Titolo = "La coscienza di Zeno"
                        },
                        new
                        {
                            ISBN = "9788806215389",
                            Anno = "1947",
                            Autore = "Primo Levi",
                            Genere = "Autobiografia",
                            Titolo = "Se questo � un uomo"
                        },
                        new
                        {
                            ISBN = "9788806181530",
                            Anno = "1940",
                            Autore = "Dino Buzzati",
                            Genere = "Romanzo",
                            Titolo = "Il deserto dei Tartari"
                        },
                        new
                        {
                            ISBN = "9780142437183",
                            Anno = "1922",
                            Autore = "Hermann Hesse",
                            Genere = "Romanzo",
                            Titolo = "Siddhartha"
                        },
                        new
                        {
                            ISBN = "9788806177908",
                            Anno = "1980",
                            Autore = "Umberto Eco",
                            Genere = "Romanzo giallo",
                            Titolo = "Il nome della rosa"
                        },
                        new
                        {
                            ISBN = "9788806173283",
                            Anno = "1926",
                            Autore = "Luigi Pirandello",
                            Genere = "Romanzo",
                            Titolo = "Uno, nessuno e centomila"
                        },
                        new
                        {
                            ISBN = "9780553296983",
                            Anno = "1947",
                            Autore = "Anna Frank",
                            Genere = "Autobiografia",
                            Titolo = "Il diario di Anna Frank"
                        },
                        new
                        {
                            ISBN = "9788806173979",
                            Anno = "1951",
                            Autore = "Marguerite Yourcenar",
                            Genere = "Romanzo",
                            Titolo = "Memorie di Adriano"
                        },
                        new
                        {
                            ISBN = "9788806171234",
                            Anno = "1984",
                            Autore = "Milan Kundera",
                            Genere = "Romanzo",
                            Titolo = "L'insostenibile leggerezza dell'essere"
                        },
                        new
                        {
                            ISBN = "9788806170847",
                            Anno = "1967",
                            Autore = "Gabriel Garc�a M�rquez",
                            Genere = "Romanzo",
                            Titolo = "Cent'anni di solitudine"
                        },
                        new
                        {
                            ISBN = "9788806170595",
                            Anno = "1981",
                            Autore = "Gabriel Garc�a M�rquez",
                            Genere = "Romanzo",
                            Titolo = "Cronaca di una morte annunciata"
                        },
                        new
                        {
                            ISBN = "9788806171844",
                            Anno = "1985",
                            Autore = "Gabriel Garc�a M�rquez",
                            Genere = "Romanzo",
                            Titolo = "Amore ai tempi del colera"
                        },
                        new
                        {
                            ISBN = "9788806172179",
                            Anno = "1960",
                            Autore = "Harper Lee",
                            Genere = "Romanzo",
                            Titolo = "Il buio oltre la siepe"
                        },
                        new
                        {
                            ISBN = "9780140283292",
                            Anno = "1957",
                            Autore = "Jack Kerouac",
                            Genere = "Romanzo",
                            Titolo = "Sulla strada"
                        },
                        new
                        {
                            ISBN = "9780140283339",
                            Anno = "1954",
                            Autore = "William Golding",
                            Genere = "Romanzo",
                            Titolo = "Il signore delle mosche"
                        },
                        new
                        {
                            ISBN = "9780316769174",
                            Anno = "1951",
                            Autore = "J.D. Salinger",
                            Genere = "Romanzo",
                            Titolo = "Il giovane Holden"
                        },
                        new
                        {
                            ISBN = "9781451673319",
                            Anno = "1953",
                            Autore = "Ray Bradbury",
                            Genere = "Distopia",
                            Titolo = "Fahrenheit 451"
                        },
                        new
                        {
                            ISBN = "9781594480006",
                            Anno = "2003",
                            Autore = "Khaled Hosseini",
                            Genere = "Romanzo",
                            Titolo = "Il cacciatore di aquiloni"
                        },
                        new
                        {
                            ISBN = "9781594483851",
                            Anno = "2007",
                            Autore = "Khaled Hosseini",
                            Genere = "Romanzo",
                            Titolo = "Mille splendidi soli"
                        },
                        new
                        {
                            ISBN = "9780060935467",
                            Anno = "1960",
                            Autore = "Harper Lee",
                            Genere = "Romanzo",
                            Titolo = "Il buio oltre la siepe"
                        },
                        new
                        {
                            ISBN = "9780553383805",
                            Anno = "1982",
                            Autore = "Isabel Allende",
                            Genere = "Romanzo",
                            Titolo = "La casa degli spiriti"
                        },
                        new
                        {
                            ISBN = "9780452290269",
                            Anno = "2006",
                            Autore = "Ildefonso Falcones",
                            Genere = "Romanzo",
                            Titolo = "La cattedrale del mare"
                        },
                        new
                        {
                            ISBN = "9780140120832",
                            Anno = "1985",
                            Autore = "Patrick S�skind",
                            Genere = "Romanzo",
                            Titolo = "Il profumo"
                        },
                        new
                        {
                            ISBN = "9780143034907",
                            Anno = "2001",
                            Autore = "Carlos Ruiz Zaf�n",
                            Genere = "Romanzo",
                            Titolo = "L'ombra del vento"
                        },
                        new
                        {
                            ISBN = "9780143116375",
                            Anno = "2008",
                            Autore = "Carlos Ruiz Zaf�n",
                            Genere = "Romanzo",
                            Titolo = "Il gioco dell'angelo"
                        },
                        new
                        {
                            ISBN = "9780452282158",
                            Anno = "1999",
                            Autore = "Tracy Chevalier",
                            Genere = "Romanzo",
                            Titolo = "La ragazza con l'orecchino di perla"
                        },
                        new
                        {
                            ISBN = "9780307389732",
                            Anno = "1985",
                            Autore = "Gabriel Garc�a M�rquez",
                            Genere = "Romanzo",
                            Titolo = "L'amore ai tempi del colera"
                        },
                        new
                        {
                            ISBN = "9780451529704",
                            Anno = "1844",
                            Autore = "Alexandre Dumas",
                            Genere = "Romanzo",
                            Titolo = "Il conte di Montecristo"
                        },
                        new
                        {
                            ISBN = "9781400031696",
                            Anno = "2002",
                            Autore = "Donna Tartt",
                            Genere = "Romanzo",
                            Titolo = "Il piccolo amico"
                        },
                        new
                        {
                            ISBN = "9780446310789",
                            Anno = "1960",
                            Autore = "Harper Lee",
                            Genere = "Romanzo",
                            Titolo = "Il buio oltre la siepe"
                        },
                        new
                        {
                            ISBN = "9780142437268",
                            Anno = "1850",
                            Autore = "Nathaniel Hawthorne",
                            Genere = "Romanzo",
                            Titolo = "La lettera scarlatta"
                        },
                        new
                        {
                            ISBN = "9780307474278",
                            Anno = "2003",
                            Autore = "Dan Brown",
                            Genere = "Romanzo giallo",
                            Titolo = "Il codice da Vinci"
                        },
                        new
                        {
                            ISBN = "9780743493469",
                            Anno = "2000",
                            Autore = "Dan Brown",
                            Genere = "Romanzo giallo",
                            Titolo = "Angeli e demoni"
                        },
                        new
                        {
                            ISBN = "9780385537858",
                            Anno = "2013",
                            Autore = "Dan Brown",
                            Genere = "Romanzo giallo",
                            Titolo = "Inferno"
                        },
                        new
                        {
                            ISBN = "9780385504225",
                            Anno = "2009",
                            Autore = "Dan Brown",
                            Genere = "Romanzo giallo",
                            Titolo = "Il simbolo perduto"
                        },
                        new
                        {
                            ISBN = "9781594633669",
                            Anno = "2015",
                            Autore = "Paula Hawkins",
                            Genere = "Thriller",
                            Titolo = "La ragazza del treno"
                        },
                        new
                        {
                            ISBN = "9780553579901",
                            Anno = "1998",
                            Autore = "George R.R. Martin",
                            Genere = "Fantasy",
                            Titolo = "Il grande inverno"
                        },
                        new
                        {
                            ISBN = "9780553106633",
                            Anno = "2000",
                            Autore = "George R.R. Martin",
                            Genere = "Fantasy",
                            Titolo = "Tempesta di spade"
                        },
                        new
                        {
                            ISBN = "9780553801507",
                            Anno = "2005",
                            Autore = "George R.R. Martin",
                            Genere = "Fantasy",
                            Titolo = "Il banchetto dei corvi"
                        },
                        new
                        {
                            ISBN = "9780553801477",
                            Anno = "2011",
                            Autore = "George R.R. Martin",
                            Genere = "Fantasy",
                            Titolo = "La danza dei draghi"
                        },
                        new
                        {
                            ISBN = "9780553386790",
                            Anno = "1996",
                            Autore = "George R.R. Martin",
                            Genere = "Fantasy",
                            Titolo = "Cronache del ghiaccio e del fuoco"
                        },
                        new
                        {
                            ISBN = "9780765365279",
                            Anno = "2010",
                            Autore = "Brandon Sanderson",
                            Genere = "Fantasy",
                            Titolo = "La via del re"
                        },
                        new
                        {
                            ISBN = "9780765365286",
                            Anno = "2014",
                            Autore = "Brandon Sanderson",
                            Genere = "Fantasy",
                            Titolo = "Parole di luce"
                        },
                        new
                        {
                            ISBN = "9780765365293",
                            Anno = "2017",
                            Autore = "Brandon Sanderson",
                            Genere = "Fantasy",
                            Titolo = "Giuramento"
                        },
                        new
                        {
                            ISBN = "9780765377135",
                            Anno = "2006",
                            Autore = "Brandon Sanderson",
                            Genere = "Fantasy",
                            Titolo = "L'ultimo impero"
                        },
                        new
                        {
                            ISBN = "9780765377142",
                            Anno = "2007",
                            Autore = "Brandon Sanderson",
                            Genere = "Fantasy",
                            Titolo = "Il pozzo dell'ascensione"
                        },
                        new
                        {
                            ISBN = "9780765377159",
                            Anno = "2008",
                            Autore = "Brandon Sanderson",
                            Genere = "Fantasy",
                            Titolo = "Il Campione delle Ere"
                        },
                        new
                        {
                            ISBN = "9780440212560",
                            Anno = "1991",
                            Autore = "Diana Gabaldon",
                            Genere = "Romanzo storico",
                            Titolo = "La straniera"
                        },
                        new
                        {
                            ISBN = "9780156028356",
                            Anno = "1982",
                            Autore = "Alice Walker",
                            Genere = "Romanzo",
                            Titolo = "Il colore viola"
                        },
                        new
                        {
                            ISBN = "9780156027991",
                            Anno = "2002",
                            Autore = "Jos� Saramago",
                            Genere = "Romanzo",
                            Titolo = "L'uomo duplicato"
                        },
                        new
                        {
                            ISBN = "9780812979657",
                            Anno = "1997",
                            Autore = "Arundhati Roy",
                            Genere = "Romanzo",
                            Titolo = "Il dio delle piccole cose"
                        },
                        new
                        {
                            ISBN = "9780375704024",
                            Anno = "1987",
                            Autore = "Haruki Murakami",
                            Genere = "Romanzo",
                            Titolo = "Norwegian Wood"
                        },
                        new
                        {
                            ISBN = "9780099482282",
                            Anno = "2002",
                            Autore = "Haruki Murakami",
                            Genere = "Romanzo",
                            Titolo = "Kafka sulla spiaggia"
                        },
                        new
                        {
                            ISBN = "9780385494243",
                            Anno = "2001",
                            Autore = "Ian McEwan",
                            Genere = "Romanzo",
                            Titolo = "L'amore ai tempi della ragione"
                        },
                        new
                        {
                            ISBN = "9781400078776",
                            Anno = "2005",
                            Autore = "Kazuo Ishiguro",
                            Genere = "Romanzo",
                            Titolo = "Non lasciarmi"
                        },
                        new
                        {
                            ISBN = "9780312428815",
                            Anno = "1993",
                            Autore = "Jeffrey Eugenides",
                            Genere = "Romanzo",
                            Titolo = "Le vergini suicide"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
